//--------------------------------------------//
// This file automatically generated by Perl. //
//               DO NOT EDIT!                 //
//--------------------------------------------//

#ifndef PMT_PmtLocalDefs_H
#define PMT_PmtLocalDefs_H
const char *const PmtLocalDefs[] = {
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
<xsd:schema xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" elementFormDefault=\"qualified\">\
	<xsd:element name=\"PmtRootElement\">\
		<xsd:complexType>\
			<xsd:sequence>\
				<xsd:element name=\"NewMd\" type=\"xsd:unsignedShort\"/>\
			</xsd:sequence>\
		</xsd:complexType>\
	</xsd:element>\
</xsd:schema>\
",
    NULL
};

#endif

