//--------------------------------------------//
// This file automatically generated by Perl. //
//               DO NOT EDIT!                 //
//--------------------------------------------//

#ifndef PMT_PmtLocalAliases_H
#define PMT_PmtLocalAliases_H
const char *const PmtLocalAliases[] = {
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
<MetadataAliases>\
	<MetadataAlias AliasKey=\"MyAlias\">\
		<AliasMember MetadataKey=\"CaptureDevice.Model\"/>\
		<AliasMember MetadataKey=\"ImageContainer.Orientation\"/>\
	</MetadataAlias>\
	<MetadataAlias AliasKey=\"exif_persist2\">\
		<AliasMember MetadataKey=\"NewMd\"/>\
	</MetadataAlias>\
</MetadataAliases>\
",
    NULL
};

#endif

