//--------------------------------------------//
// This file automatically generated by Perl. //
//               DO NOT EDIT!                 //
//--------------------------------------------//

#ifndef PMT_PmtLocalTable_H
#define PMT_PmtLocalTable_H
const char *const PmtLocalTable[] = {
    "<?xml version=\"1.0\"?>\
<!DOCTYPE TRANSLATION>\
<TRANSLATION CreatedTime=\"Tues Jun 12 12:36:00 2001\">\
    <ENTRY Key=\"NewMd\">\
        <EXIF Tag=\"60010\" Type=\"ushort\" Location=\"APP3_IFD0\" Translator=\"builtin2ushort\"/>\
        <TIFF Tag=\"60010\" Type=\"ushort\" Location=\"IFD_EXIF\" Translator=\"builtin2ushort\"/>\
    </ENTRY>\
</TRANSLATION>\
",
    NULL
};

#endif

